### ISSUE TITLE
Trace/Errors logs without "OperationId" property in custom Operations

### ISSUE THREAD

**Issue by lommez** [microsoft/ApplicationInsights-dotnet#2513]
Hi,

When starting new custom operation from the TelemetryClient, the trace and error logs doesn't have an operation id.
In that way i can't the see the nested logs inside the operation.

I'm using .Net 5.0 and dotnet-isolated runtime function:

![image](https://user-images.githubusercontent.com/10900667/148866075-ebbeccdf-b46a-408a-8db6-881e3b9afe76.png)

![image](https://user-images.githubusercontent.com/10900667/148866097-12a223cc-8ba3-4f02-b486-15501eeefcf0.png)

![image](https://user-images.githubusercontent.com/10900667/148866185-669fe499-12bc-4614-b4fa-2eb6bc82f766.png)

![image](https://user-images.githubusercontent.com/10900667/148866231-209b4688-abda-4fe0-b5ae-da35c7c22ddb.png)

![image](https://user-images.githubusercontent.com/10900667/148866278-b9ae794d-f429-483e-8dfc-8f134c9fe653.png)

Am I missing something? Or is this a bug?

**Comment by cijothomas** [comment]
The code is incorrect because it is simply newing up a TelemetryConfiguration without adding the required initializers, so correlation is not likely to work.

Which doc did you follow to add telemetry in Azure functions?

**Comment by lommez** [comment]
@cijothomas, but i've registred the TelemetryConfiguration as singleton and injecting into the function class. It was suppose to work it.

I've read from here [https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#logging-services](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#logging-services)

**Comment by cijothomas** [comment]
The doc clearly state "Don't register your own TelemetryConfiguration", but the snippet you shared above is doing exactly this.

**Comment by cijothomas** [comment]
Your code snippet (shared in original post) is *not* doing that. You are creating new TelemetryConfiguration(), which is incorrect.

**Comment by lommez** [comment]
@cijothomas, if you pay atention in my code, you are going to realize that i'm injecting the TelemetryConfiguration AND NOT creating a new one! And it is registred as SINGLETON.
Please read carefully what i've implemented.

**Comment by cijothomas** [comment]
I see new TelemetryConfiguration(instrumentationKey), which is incorrect. If you are not following the doc, I cannot help here.

**Comment by lommez** [comment]
The question is, do you really want to help me???
Instead of sending messages that my code is wrong, why dont you say what is wrong? You are spending your and my time with messages that really doesn't help!

By the way, i tried to use TelemetryConfiguration.CreateDefault(), and is still not working as expected.

I hope that in new a reply, you tell me something that really is going to help....

Thanks!

**Comment by cijothomas** [comment]
> Instead of sending messages that my code is wrong, why dont you say what is wrong?

Copying my earlier response as is: "You are creating new TelemetryConfiguration(), which is incorrect.".
If you use "TelemetryConfiguration.CreateDefault()", it is still incorrect. 

The doc has made it clear already. And included code example as well: https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-class-library?tabs=v2%2Ccmd#log-custom-telemetry-in-c-functions

Do not create a new TelemetryConfigure. Simply retrieve the one already added by Functions using DI. The above code shows that as well.

**Comment by lommez** [comment]
@pharring, do i need to install an extra nuget package?
Because the TelemetryConfiguration was not registred

**Comment by pharring** [comment]
The docs say Microsoft.Azure.WebJobs.Logging.ApplicationInsights
There's also a section to configure Application Insights in host.json:
https://docs.microsoft.com/azure/azure-functions/functions-host-json#applicationinsights

**Comment by lommez** [comment]
@pharring
I've added that package, but is still not working.
Here is exception that occurs because the TelemetryConfiguration is not registred:

![image](https://user-images.githubusercontent.com/10900667/149045409-026d8f8a-70a8-43ab-a391-ff91cc6faec4.png)

To reproduce the error i've created a repository with a sample in the link below:

[https://github.com/lommez/AzureFunctionsAppInsights](https://github.com/lommez/AzureFunctionsAppInsights)

**Comment by lommez** [comment]
I found that the documentation is not up to date.
The correct away to inject is like that:
```IOptions<TelemetryConfiguration>```

But even using that instance, the logs in Application Insights, shouldn't be nested in the custom operation?

![image](https://user-images.githubusercontent.com/10900667/149192275-3f77d3aa-1480-4ba8-937c-4a9287ba0f9b.png)


![image](https://user-images.githubusercontent.com/10900667/149191324-e00fe63c-26c7-42b0-8dfb-00a7c845c4a9.png)

**Comment by pharring** [comment]
Glad you figured it out. Please enter a doc bug via the feedback link at the bottom of the relevant page.

**Comment by Shishkovskiy** [comment]
@lommez  Could you provide the link?

**Comment by lommez** [comment]
@Shishkovskiy,

That documention is not up to date:

[https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-class-library?tabs=v2%2Ccmd#log-custom-telemetry-in-c-functions](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-class-library?tabs=v2%2Ccmd#log-custom-telemetry-in-c-functions)

Is not possible to inject the Telemetry like is said

**Comment by cijothomas** [comment]
Closing, nothing actionable in this repo.
