### ISSUE TITLE
Dependency Telemetries assigned to wrong operation-id in webjobs

### ISSUE THREAD

**Issue by federicobarera** [microsoft/ApplicationInsights-dotnet#903]
## Repro Steps
1. Create a .NET (Full Framework) Console App
2. Install the Web Jobs Framework
3. Install Application Insights (tested with 2.5.1). Make sure you have the DependencyModule configured in the AppInsights.config
4. Create a Function to receive a QueueMessage in the following way:
**NOTE: The message has to contain a RootOperationId and a ParentId**
```
public async Task ProcessAsync([QueueTrigger([YOUR-TRIGGER])] string message, TextWriter log) {

  var telemetryOperation = this.BeginTelemetryOperation(message);

  try {
    ... [http-dependency]
    ... [http-dependency]
  }
  finally {
    telemetryClient.StopOperation(telemetryOperation );
  }
}

private Microsoft.ApplicationInsights.Extensibility.IOperationHolder<RequestTelemetry> BeginTelemetryOperation(message)
{
  RequestTelemetry requestTelemetry = new RequestTelemetry { Name = $"Dequeue from [queue]" };
  if (message != null)
  {
    if (message.RootId != null && message.ParentId != null)  {
       requestTelemetry.Context.Operation.Id = message.RootId.ToString();
       requestTelemetry.Context.Operation.ParentId = message.ParentId.ToString();
    }
  }
  var operation = telemetryClient.StartOperation(requestTelemetry);
  return operation;
}
```
5. Put some load on the queue and monitor behavior

##  Actual Behavior
dependencies from other messages are correlated to the wrong operation-id
![image](https://user-images.githubusercontent.com/6658124/45064679-7a000600-b0f8-11e8-8dac-c58739b17e41.png)

## Version Info 
SDK Version : 2.5.1
.NET Version : 4.6.1					
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) :VisualStudio
OS : Win10
Hosting Info (IIS/Azure WebApps/ etc) : Azure Web Job (console app)

**Comment by lmolkova** [comment]
which version of WebJobs SDK are you running? How did you configure the dependency collection and TelemteryConfiguration?

I believe you did not add [OperationCorrelationTelemtryIntitializer](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/master/src/Microsoft.ApplicationInsights/Extensibility/OperationCorrelationTelemetryInitializer.cs) into the TelemetryConfiguration and web jobs do not do it by default.

We are working on better story in WebJobs 3.0 - you won't need to configure anything: https://github.com/Azure/azure-webjobs-sdk/releases/tag/v3.0.0-beta8

**Comment by federicobarera** [comment]
Hi @lmolkova 

We are currently using **2.0.0**

TelemetryConfiguration is added using the `TelemetryConfiguration.Active' singleton

```
TelemetryConfiguration.Active.InstrumentationKey = configProvider.ApplicationInsights.InstrumentationKey;
TelemetryConfiguration.Active.TelemetryInitializers.Add(new CloudRoleTelemetryInitializer("[WORKER]"));
```

dependency collection is performed using the default modules coming with nuget installer:

```
<?xml version="1.0" encoding="utf-8"?>
<ApplicationInsights xmlns="http://schemas.microsoft.com/ApplicationInsights/2013/Settings">
	<TelemetryInitializers>
		<Add Type="Microsoft.ApplicationInsights.DependencyCollector.HttpDependenciesParsingTelemetryInitializer, Microsoft.AI.DependencyCollector"/>
		<Add Type="Microsoft.ApplicationInsights.WindowsServer.AzureRoleEnvironmentTelemetryInitializer, Microsoft.AI.WindowsServer"/>
		<Add Type="Microsoft.ApplicationInsights.WindowsServer.AzureWebAppRoleEnvironmentTelemetryInitializer, Microsoft.AI.WindowsServer"/>
		<Add Type="Microsoft.ApplicationInsights.WindowsServer.BuildInfoConfigComponentVersionTelemetryInitializer, Microsoft.AI.WindowsServer"/>
	</TelemetryInitializers>
	<TelemetryModules>
		<Add Type="Microsoft.ApplicationInsights.DependencyCollector.DependencyTrackingTelemetryModule, Microsoft.AI.DependencyCollector">
			<ExcludeComponentCorrelationHttpHeadersOnDomains>
				<!-- 
        Requests to the following hostnames will not be modified by adding correlation headers.         
        Add entries here to exclude additional hostnames.
        NOTE: this configuration will be lost upon NuGet upgrade.
        -->
				<Add>core.windows.net</Add>
				<Add>core.chinacloudapi.cn</Add>
				<Add>core.cloudapi.de</Add>
				<Add>core.usgovcloudapi.net</Add>
				<Add>localhost</Add>
				<Add>127.0.0.1</Add>
			</ExcludeComponentCorrelationHttpHeadersOnDomains>
			<IncludeDiagnosticSourceActivities>
				<Add>Microsoft.Azure.EventHubs</Add>
				<Add>Microsoft.Azure.ServiceBus</Add>
			</IncludeDiagnosticSourceActivities>
		</Add>
		<Add Type="Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.PerformanceCollectorModule, Microsoft.AI.PerfCounterCollector">
			<!--
      Use the following syntax here to collect additional performance counters:
      
      <Counters>
        <Add PerformanceCounter="\Process(??APP_WIN32_PROC??)\Handle Count" ReportAs="Process handle count" />
        ...
      </Counters>
      
      PerformanceCounter must be either \CategoryName(InstanceName)\CounterName or \CategoryName\CounterName
      
      NOTE: performance counters configuration will be lost upon NuGet upgrade.
      
      The following placeholders are supported as InstanceName:
        ??APP_WIN32_PROC?? - instance name of the application process  for Win32 counters.
        ??APP_W3SVC_PROC?? - instance name of the application IIS worker process for IIS/ASP.NET counters.
        ??APP_CLR_PROC?? - instance name of the application CLR process for .NET counters.
      -->
		</Add>
		<Add Type="Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.QuickPulse.QuickPulseTelemetryModule, Microsoft.AI.PerfCounterCollector"/>
		<Add Type="Microsoft.ApplicationInsights.WindowsServer.DeveloperModeWithDebuggerAttachedTelemetryModule, Microsoft.AI.WindowsServer"/>
		<Add Type="Microsoft.ApplicationInsights.WindowsServer.UnhandledExceptionTelemetryModule, Microsoft.AI.WindowsServer"/>
		<Add Type="Microsoft.ApplicationInsights.WindowsServer.UnobservedExceptionTelemetryModule, Microsoft.AI.WindowsServer">
			<!--</Add>
    <Add Type="Microsoft.ApplicationInsights.WindowsServer.FirstChanceExceptionStatisticsTelemetryModule, Microsoft.AI.WindowsServer">-->
		</Add>
	</TelemetryModules>
	<TelemetryProcessors>
		<Add Type="Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.QuickPulse.QuickPulseTelemetryProcessor, Microsoft.AI.PerfCounterCollector"/>
		<Add Type="Microsoft.ApplicationInsights.Extensibility.AutocollectedMetricsExtractor, Microsoft.ApplicationInsights"/>
    <Add Type="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.AdaptiveSamplingTelemetryProcessor, Microsoft.AI.ServerTelemetryChannel">
      <MaxTelemetryItemsPerSecond>5</MaxTelemetryItemsPerSecond>
      <ExcludedTypes>Event</ExcludedTypes>
    </Add>
	</TelemetryProcessors>
	<TelemetryChannel Type="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.ServerTelemetryChannel, Microsoft.AI.ServerTelemetryChannel"/>
<!-- 
    Learn more about Application Insights configuration with ApplicationInsights.config here: 
    http://go.microsoft.com/fwlink/?LinkID=513840
    
    Note: If not present, please add <InstrumentationKey>Your Key</InstrumentationKey> to the top of this file.
  --></ApplicationInsights>
```

**Comment by federicobarera** [comment]
TelemetryConfiguration.Active should call TelemetryConfigurationFactory which should register that initializer

**Comment by lmolkova** [comment]
ok, thanks, could you please provide more info:

1. in Log Analytics, please query all telemetry for  a particular operation, parent id, operation id and id, type (request/dependency), name and operation name,timestamp are essential fields  we'll be looking into
2. mark dependencies are correlated to the wrong request
3. mark dependencies are correlated to the right request
4. what parent id and root id were passed along the message

**Comment by lmolkova** [comment]
can you send it via email (lmokova at microsoft.com)?

**Comment by federicobarera** [comment]
@lmolkova I've sent you an email with more details. Please don't hesitate to contact me directly if anything else is needed

**Comment by emilbm** [comment]
Was this actually fixed in 3.0? I'm experiencing similar symptoms with Webjobs 3.0.

**Comment by Rfaering** [comment]
I am also seeing this problem for our webjobs 3.0

**Comment by lmolkova** [comment]
@emilbm @Rfaering can you please provide more info of the issue you experience with 3.0 Web Jobs?

- which telemetry items have wrong operation id? It is requests, dependencies, traces, etc?
- examples of such telemetry items (please strip anything sensitive) and provide all properties - the easiest was to export data from kusto

**Comment by federicobarera** [comment]
Hi @lmolkova,

two years later and in a different place we are still experiencing the issue.
This time in `Microsoft.ApplicationInsights.AspNetCore@2.12.0`

We might just open a support ticket with Microsoft to look into it

**Comment by federicobarera** [comment]
Hi, 

I think is worth sharing here the result of the investigation done with ms support, hopefully it will help other ppl experiencing the same issue.
There is a bug in the System.Diagnostic.DiagnosticSource namespace around the code written to support Activities for older framework (.net 4.#). 

> The problem appears to be where the injected diagnostic listener doesn’t account for the behaviour within .Net 4.# where the framework might chain calls to the same URI on the same connection in a singular async context

Beware, this doesn't only impact wrong correlations, but propagation of the wrong activity trace/headers via http headers.

**Comment by peterwind** [comment]
@federicobarera: Did you find a workaround? We are experiencing the exact same problem where a function based on the QueueTrigger gets a wrong operationId.

**Comment by federicobarera** [comment]
@peterwind 
For us the issue affects: API -> HTTP -> API.

The workaround (which we are currently testing), is to add a DelegatingHandler to HttpClients. I am posting it below

```
public class QueueHttpHandler : DelegatingHandler
    {
        // We store a mapping from service point to semaphore slim. This lets us properly limit concurrent requests for individual URLs
        // based on the mapping from URI (service point) to semaphore slim.
        private ConditionalWeakTable<ServicePoint, SemaphoreSlim> _servicePointMap = new ConditionalWeakTable<ServicePoint, SemaphoreSlim>();

        protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            var servicePoint = ServicePointManager.FindServicePoint(request.RequestUri);

            // This assumes HTTP/1.1, one request per connection (which is the case by default anyways)
            var queue = _servicePointMap.GetValue(servicePoint, sp => new SemaphoreSlim(sp.ConnectionLimit, sp.ConnectionLimit));

            await queue.WaitAsync();
            try
            {
                var response = await base.SendAsync(request, cancellationToken);
                response.Content = new QueueContent(response.Content, queue);
                return response;
            }
            catch
            {
                // If there's an exception producing the response, release the semaphore slim
                queue.Release();
                throw;
            }
        }

        // This content is responsible releasing the semaphore when the content is fully read
        private class QueueContent : HttpContent
        {
            private readonly HttpContent _httpContent;
            private readonly SemaphoreSlim _queue;

            public QueueContent(HttpContent httpContent, SemaphoreSlim queue)
            {
                _httpContent = httpContent;
                _queue = queue;
            }

            protected override async Task SerializeToStreamAsync(Stream stream, TransportContext context)
            {
                try
                {
                    await _httpContent.CopyToAsync(stream, context);
                }
                finally
                {
                    // Release the semaphore slim after the copy
                    _queue.Release();
                }
            }

            protected override bool TryComputeLength(out long length)
            {

                var contentLength = _httpContent.Headers.ContentLength;
                if (contentLength == null)
                {
                    length = 0;
                    return false;
                }

                length = contentLength.Value;
                return true;
            }
        }
    }
```

and in service registration...

```
services
.AddTransient<QueueHttpHandler>()
.AddHttpClient<...> ()
.AddHttpMessageHandler<QueueHttpHandler>()
```
